#!/usr/bin/env python3
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
path = ROOT / "skills/cogentnexus/scripts/workflow.py"
text = path.read_text(encoding="utf-8")
old = '''        value["taskId"]="WF-TEST-KILLED-CONTROLLER"\n        value["steps"][0]["executor"]={"type":"command","argv":[py,"-c","import time;from pathlib import Path;Path('runner-started.txt').write_text('started');time.sleep(5);Path('killed.txt').write_text('survived')"]}\n        value["steps"][0]["outputs"]=["killed.txt"]\n        value["steps"][0]["validator"]={"argv":[py,"-c","from pathlib import Path;assert Path('killed.txt').read_text()=='survived'"]}\n        manifest.write_text(json.dumps(value),encoding="utf-8")\n        initialize(root,manifest,operator_unbound=True,operator_reason="self-test killed controller")\n        controller=subprocess.Popen([py,str(Path(__file__).resolve()),"--root",str(root),"run",value["taskId"]],stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)\n        killed_flow=Workflow(root,value["taskId"]); deadline=time.monotonic()+15; runner_pid=None\n        while time.monotonic()<deadline:\n            runner_pid=killed_flow.state()["steps"]["one"].get("runnerPid")\n            if runner_pid and runner_pid != controller.pid and (root/"runner-started.txt").is_file() and process_alive(runner_pid): break\n            time.sleep(.05)\n        assert runner_pid and runner_pid != controller.pid and process_alive(runner_pid)\n        controller.terminate(); controller.wait(timeout=5)\n        fenced=supervise_workflows(root,execute=True,maximum=1)\n        observed=next(x for x in fenced["workflows"] if x.get("taskId")==value["taskId"])\n        assert observed["runnerAlive"] and not any(x.get("taskId")==value["taskId"] for x in fenced["actions"])\n        deadline=time.monotonic()+5\n        while time.monotonic()<deadline and process_alive(runner_pid): time.sleep(.05)\n        recovered=run_workflow(root,value["taskId"])\n'''
new = '''        value["taskId"]="WF-TEST-KILLED-CONTROLLER"\n        value["steps"][0]["executor"]={"type":"command","argv":[py,"-c","import time;from pathlib import Path;Path('runner-started.txt').write_text('started');deadline=time.monotonic()+30;release=Path('release-runner.txt');\nwhile not release.exists() and time.monotonic()<deadline: time.sleep(.05)\nPath('killed.txt').write_text('survived')"]}\n        value["steps"][0]["outputs"]=["killed.txt"]\n        value["steps"][0]["validator"]={"argv":[py,"-c","from pathlib import Path;assert Path('killed.txt').read_text()=='survived'"]}\n        manifest.write_text(json.dumps(value),encoding="utf-8")\n        initialize(root,manifest,operator_unbound=True,operator_reason="self-test killed controller")\n        controller=subprocess.Popen([py,str(Path(__file__).resolve()),"--root",str(root),"run",value["taskId"]],stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)\n        killed_flow=Workflow(root,value["taskId"]); deadline=time.monotonic()+20; runner_pid=None\n        while time.monotonic()<deadline:\n            runner_pid=killed_flow.state()["steps"]["one"].get("runnerPid")\n            if runner_pid and runner_pid != controller.pid and (root/"runner-started.txt").is_file() and process_alive(runner_pid): break\n            time.sleep(.05)\n        assert runner_pid and runner_pid != controller.pid and process_alive(runner_pid)\n        controller.terminate(); controller.wait(timeout=5)\n        fenced=supervise_workflows(root,execute=True,maximum=1)\n        observed=next(x for x in fenced["workflows"] if x.get("taskId")==value["taskId"])\n        assert observed["runnerAlive"] and not any(x.get("taskId")==value["taskId"] for x in fenced["actions"])\n        (root/"release-runner.txt").write_text("release")\n        deadline=time.monotonic()+10\n        while time.monotonic()<deadline and process_alive(runner_pid): time.sleep(.05)\n        recovered=run_workflow(root,value["taskId"])\n'''
if text.count(old) != 1:
    raise SystemExit(f"expected one self-test block, found {text.count(old)}")
path.write_text(text.replace(old, new, 1), encoding="utf-8", newline="\n")
print("Applied deterministic killed-controller self-test handshake")
